prefix schema: <http://schema.org/>
prefix :      <http://localhost:9000/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix event:   <http://localhost:9000/event/>

SELECT * WHERE {
	?place a schema:Place .
	?place schema:address ?address .
	?address schema:streetAddress ?local .
}
